project:
   type: "website"
   output-dir: "docs"

website:
  description: "A blog built with Quarto"
  site-url:  https://israel-ggb.github.io # you must change this appropriately for RSS feeds to work properly
  title: "ALOKEME Israel"
  page-footer: "© 2026 ALOKEME Israel. All rights reserved|Build with Quarto."
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: Blog.qmd
      - text: "CV"
        file: CV.qmd 
      - text: "Coding projects"
        file: coding.qmd
    right:
      - icon: github
        href: https://github.com/Israel-ggb
format:
  html:
    theme:
      - Flatly
      - brand
    css: styles.css

editor: visual

